name = input("Enter your name: ")
race = input("State your race! (human - elf - dwarf - orc): ")
if race == "human":
    print("You are a human!")
    print("     MM     ")
    print("    /..\ |  ")
    print("    \--/ |  ")
    print("     WW  |  ")
    print("     |   |  ")
    print("  *--+---+  ")
    print("     |   |  ")
    print("     ^      ")
    print("    / \     ")
    print(" ")
    print("Here is " + name + " the Brave Man!")
    
elif race == "elf":
    print("     ~~     ")
    print("   q/..\p   ")
    print("    \ -/    ")
    print("  *  |  |\  ")
    print("  |--+--| | ")
    print("  v  |  |/  ")
    print("     ^      ")
    print("    / \     ")
    print(" ")
    print("Here is " + name + " the Cunning Elf!")
    
elif race == "dwarf":
    print("     $$      ")
    print("    /..\     ")
    print("  q \ o/ p   ")
    print("  |--+---|   ")
    print("    / \      ")
    print(" ")
    print("Here is " + name + " the Mighty Dwarf!")
    
elif race == "orc":
    print("     ^^     ")
    print("   / oo\    ")
    print("   \v-v/    ")
    print("  ^  |  ^   ")
    print("  |--+--|   ")
    print("     |      ")
    print("     ^      ")
    print("    / \     ")
    print(" ")
    print("Here is " + name + " the Ugly Orc!")
else :
    print("You fail at life")
    print("Loser LOL")
